name: Deploy Angular App to Firebase

on:
  push:
    branches:
      - main
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
#      - name: Run Tests
#        run: npm test -- --watch=false --browsers=ChromeHeadless
      - name: Generate environment.prod.ts
        run: |
          printf "export const environment = {
            production: true,
            firebase: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}'
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            }
          };" > ./src/environments/environment.prod.ts
      - name: Build Angular App
        run: npm run build --prod
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate with Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT_KEY}" > /tmp/firebase-key.json
          gcloud auth activate-service-account --key-file=/tmp/firebase-key.json
      - name: Deploy to Firebase Hosting
        run: firebase deploy
